### PR TITLE
add Windows support for capture-stream

### LINKED ISSUE #191: Windows support for `capture-stream` feature
I'm currently using the `pcap-async` crate to perform packet capturing in asynchronous code.
I'm thinking about switching to this crate due to the Windows support via Npcap/WinPcap. But you write that the `capture-stream` feature is only supported on Linux and macOS.

What is the reason for that? Can this be easily fixed?

### PR DESCRIPTION
**Pull request by Freax13**
This PR adds Windows support for capture-stream.

Closes #191

### CODE REVIEW

**Comment by ColinFinck** [comment]
I really hope we can see this in a release soon!

CC @Wojtek242

**Comment by Wojtek242** [comment]
Thanks for the PR @Freax13! I appreciate it and apologies for the delay in responding. I only check in every few months given where this project is at.

This looks like a good PR and would ultimately want to see it merged. The CI however fails as the newer windows-sys crate version no longer works with our MSRV. 

With that said, the stream feature was never required to work on the MSRV due to there being no chance for that ever happening with a dependency on tokio. Do you think it would be possible to hide the newer windows-sys dependency behind the stream feature flag? That way pcap with no features would still work on MSRV and the stream feature could work on a newer rustc version.

**Comment by Wojtek242** [comment]
I would also appreciate some tests for the new feature. I don't work on Windows so I can't even test this manually. I would be willing to relax the MSRV if you could instead provide some unit tests for this MR.

**Comment by Freax13** [comment]
> Thanks for the PR @Freax13! I appreciate it and apologies for the delay in responding. I only check in every few months given where this project is at.
> 
> This looks like a good PR and would ultimately want to see it merged. The CI however fails as the newer windows-sys crate version no longer works with our MSRV.
> 
> With that said, the stream feature was never required to work on the MSRV due to there being no chance for that ever happening with a dependency on tokio. Do you think it would be possible to hide the newer windows-sys dependency behind the stream feature flag? That way pcap with no features would still work on MSRV and the stream feature could work on a newer rustc version.

I reverted the windows-sys bump and inlined the one constant (`INFINITE`) I needed from the newer version.

> I would also appreciate some tests for the new feature. I don't work on Windows so I can't even test this manually. I would be willing to relax the MSRV if you could instead provide some unit tests for this MR.

While I understand the desire for unit tests, I'm not sure how we'd implement them. My main concerns are false positive errors with missing permissions and that I'm not sure how we could generate traffic on a known device. I assume those are also the reasons, this crate currently doesn't have unit tests for active devices (except for `tap_tests.rs`, but AFAICT those tests aren't run in CI).

**Comment by Freax13** [comment]
1f53e0c419c6e70aac37a1ef9a8531845b96a418 broke CI on Windows. This should be fixed by a99e9ccb0a199459261ff79ef16b110fa44487a7.

**Comment by Wojtek242** [comment]
Brilliant, thanks for the PR and addressing the MSRV issues! I can't test if this works, but I trust you guys tested it.

I will push to crates.io tonight or within the next few days.

**Pull request merged**
