### PR TITLE
Bump windows-sys to 0.59.0

### PR DESCRIPTION
**Pull request by chantra**
Simple windows-sys version bump to the latest published crate version.

### CODE REVIEW

**Comment by Wojtek242** [comment]
Hi @chantra, thanks for the PR, but based on the build outputs: https://github.com/rust-pcap/pcap/actions/runs/11135749919/job/32117440201?pr=369 you will need to ammend the code as well. Let me know if you need help.

You can ignore the lints as that is currently also a problem on main.

**Comment by chantra** [comment]
Thanks @Wojtek242 ,

I will update the PR accordingly. I think that now that you authorized this PR to run the GitHub actions, update should do too, so this may help. I don’t have a windows setup handy, but I am fairly confident I should be able to cross-compile easily with cargo.

**Comment by chantra** [comment]
@Wojtek242 ok, it seems I can't get the CI to run without approval. 

This now builds with:
```
cargo build --target=x86_64-pc-windows-gnu
```

**Comment by qrnch-jan** [comment]
I apologize for PR-sniping you; I didn't see this PR before making https://github.com/rust-pcap/pcap/pull/378

Your updated is incomplete -- it's missing fixes that are unveiled by the `capture-stream` feature (always build/test using `--all-features` just to be sure).  You should merge those fixes from my PR to yours and then I'll close mine.

**Comment by chantra** [comment]
> I apologize for PR-sniping you; I didn't see this PR before making #378
> 
> Your updated is incomplete -- it's missing fixes that are unveiled by the `capture-stream` feature (always build/test using `--all-features` just to be sure). You should merge those fixes from my PR to yours and then I'll close mine.

Thanks @qrnch-jan for the heads up. I am totally fine with your PR making it through.
I will close this one in favor of your.

**Pull request closed without merging**
