### PR TITLE
Add a into_state private method and remove 2 transmute

### PR DESCRIPTION
**Pull request by Stargateur**
This simply remove 2 unnecessary transmute.

### CODE REVIEW

**Comment by Wojtek242** [comment]
Merged this manually due to merge conflicts

**Comment by Wojtek242** [comment]
FYI, I had to revert this change as it was causing segmentation faults (see #254). However, if there is non-segmentation faulting way to implement this, it would be very welcome.

**Comment by Stargateur** [comment]
I don't understand how that possible, I think this change reveal an UB somewhere else in the code.

**Comment by Stargateur** [comment]
The problem is the Drop implementation:

```rust
impl<T: State + ?Sized> Drop for Capture<T> {
    fn drop(&mut self) {
        unsafe { raw::pcap_close(self.handle.as_ptr()) }
    }
}
```

**Comment by Stargateur** [comment]
We should encapsulate `handle: NonNull<raw::pcap_t>,` into a type that have drop implement to avoid this trap it in future.

**Comment by Wojtek242** [comment]
If you would like to submit a PR with it, it would be welcome

**Pull request merged**
