### PR TITLE
Use a more reliable command to DL winpcap on windows

### PR DESCRIPTION
**Pull request by Stargateur**
It's look `(New-Object System.Net.WebClient).DownloadFile` is a sort of async way to download file. Invoke-WebRequest is more "slow" according to what I found but that work perfectly for our need, it's basically curl. This should fix our problem.

### CODE REVIEW

**Comment by Wojtek242** [comment]
I'm not sure this will fix the issue as the problem seems to be with a missing DLL, but windows is black magic to me so might as well try it.

**Comment by Wojtek242** [comment]
Nope, still a problem: https://github.com/rust-pcap/pcap/runs/7892831644?check_suite_focus=true

**Comment by Wojtek242** [comment]
I guess it's a problem with autohotkey - I remember when I was fixing the old pipeline when i took over that the Windows way of automatically installing exes was with another program that hits the right buttons on the GUI. Basically, if you want a CLI installer you need an msi file, and wpcap doesn't have one by default. Previously, I did find one on some random guy's website and it's probably still there. The correct solution would probably to move to npcap whose developers say they are willing to provide CLI installer access for open source projects.

**Comment by Wojtek242** [comment]
AFAIK, you need to pay for the OEM version or [contact the npcap developers](https://github.com/rust-pcap/pcap/issues/134) as you would need `/S (Silent install, Npcap OEM only)`. If you would like to implement it, go ahead.

**Comment by Stargateur** [comment]
> AFAIK, you need to pay for the OEM version or [contact the npcap developers](https://github.com/rust-pcap/pcap/issues/134) as you would need `/S (Silent install, Npcap OEM only)`. If you would like to implement it, go ahead.

pffff.... honestly npcap policy is...

**Pull request merged**
