### PR TITLE
more simple way to run ci for windows

### PR DESCRIPTION
**Pull request by Stargateur**
Quite ugly but should work as long as winpcap "official" installer. Honestly, that good enough for windows :p

### CODE REVIEW

**Comment by Stargateur** [comment]
I'm telling you I'm seriously consider dropping windows test support...

**Comment by Stargateur** [comment]
maybe:

```yaml
          cinst -y winpcap --version 4.1.3.20161116
          cinst -y winpcap --version 4.1.3.20161116
          cinst -y winpcap --version 4.1.3.20161116
          cinst -y winpcap --version 4.1.3.20161116
          cinst -y winpcap --version 4.1.3.20161116
          cinst -y winpcap --version 4.1.3.20161116
          cinst -y winpcap --version 4.1.3.20161116
```

https://github.com/chocolatey-community/chocolatey-packages/tree/master/automatic/winpcap is really dirty from what I understand there is not really any check or anything, if install is not done in 30s too bad ! maybe with 7 install the risk to fail install would be ok....

**Comment by Wojtek242** [comment]
> maybe:
> 
> ```yaml
>           cinst -y winpcap --version 4.1.3.20161116
>           cinst -y winpcap --version 4.1.3.20161116
>           cinst -y winpcap --version 4.1.3.20161116
>           cinst -y winpcap --version 4.1.3.20161116
>           cinst -y winpcap --version 4.1.3.20161116
>           cinst -y winpcap --version 4.1.3.20161116
>           cinst -y winpcap --version 4.1.3.20161116
> ```
> 
> https://github.com/chocolatey-community/chocolatey-packages/tree/master/automatic/winpcap is really dirty from what I understand there is not really any check or anything, if install is not done in 30s too bad ! maybe with 7 install the risk to fail install would be ok....

Rather than trying cinst N times, one could always wrap it in a while loop of some sort and proceeding if the DLL does not exist

**Comment by Wojtek242** [comment]
Thanks for your efforts! This motivated me to reach out to npcap as per #134 and now we have npcap for windows CI #273

**Pull request closed without merging**
